# Generated by Django 3.1.5 on 2021-02-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('STD', 'base employee'), ('MGR', 'manager'), ('CEO', 'ceo')], max_length=25)),
                ('emp_name', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='emr.employee')),
            ],
        ),
    ]
