# Generated by Django 3.1.5 on 2021-02-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_auto_20210201_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='manager',
            new_name='manager_name',
        ),
    ]
