# Generated by Django 3.1.5 on 2021-02-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0003_auto_20210201_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
